theme: jekyll-theme-slate
title: WELCOME
description: I'm Nicolas Fache an undergraduate student at the California Polytechnic Institute, San Luis Obispo.
description: Here are a few different pages about my past work and current projects along with my contact information!
